# Generated by Django 5.0.3 on 2024-05-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0003_ordermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='orderitems',
            new_name='ordereditems',
        ),
    ]
