# Generated by Django 5.0 on 2024-06-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0005_rename_userid_customermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
    ]
